### ISSUE TITLE
I would Like to add more to the readme.md

### ISSUE THREAD

**Issue by NS007-dev** [Coders-Evoke-Community/resources-for-community#5]
@Ayan-thecodeking , I would like to add more resources, and items to the readme.
I could put resources in tables set out like this:

### HTML:

| Resource | Description |
| ---------- | -------------|
| Resource1 | what it is for |

Or I could put them all in a list:

### CSS:
- resource1: what it is for.

I would be happy to help with adding content to the repository, thank you.

**Comment by Ayan-thecodeking** [comment]
ya sure @CodingSpecies go ahead ...great to see you here :)
