### ISSUE TITLE
Please can I join this organisation?

### ISSUE THREAD

**Issue by NS007-dev** [Coders-Evoke-Community/resources-for-community#7]
Is it possible for me to join this organisation? Thank you.

**Comment by Ayan-thecodeking** [comment]
> Is it possible for me to join this organisation? Thank you.

ya sure @CodingSpecies ...let me know aare you there in our discord server ??

**Comment by NS007-dev** [comment]
No, I'm not on discord, Is it possible for me to only be part on github please? Thank you.

**Comment by vedanthv** [comment]
> No, I'm not on discord, Is it possible for me to only be part on github please? Thank you.

Go ahead and raise an issue here https://github.com/Coders-Evoke-Community/support#guide

**Comment by NS007-dev** [comment]
@vedanthv @Ayan-thecodeking thank you. I also did make a pr to add more sections in #8
